[package]
name = "trustrun-contract"
version = "0.1.5"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
hex = { version = "0.4", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
wit-bindgen = { version = "0.49", default-features = false, features = ["macros", "realloc"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true
